<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('health_sub_districts', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->foreignId('district_id')->nullable()->references('id')->on('districts')->onDelete('RESTRICT')->onUpdate('CASCADE');
            $table->foreignId('created_by')->nullable()->references('id')->on('users')->constrained()->onUpdate('cascade')->onDelete('restrict');
            $table->timestamps();
        });

        DB::statement("
    INSERT INTO `health_sub_districts`(`name`,`district_id`) VALUES
    ('Buikwe North',1),
    ('Bukomansimbi',2),
    ('Gomba',3),
    ('Kalungu East',4),
    ('Kalungu West',4),
    ('Bbaale',5),
    ('Ntenjeru North',5),
    ('Ntenjeru South',5),
    ('Bamunanika',6),
    ('Katikamu North',6),
    ('Katikamu South',6),
    ('Kabula',7),
    ('Bukoto Central',8),
    ('Bukoto East',8),
    ('Masaka Municipality',8),
    ('Busujju (Mwera)',9),
    ('Mityana North (Kyantungo)',9),
    ('Mityana South',9),
    ('Mawokota North',10),
    ('Mawokota South',10),
    ('Mukono North',11),
    ('Mukono South',11),
    ('Nakifuma',11),
    ('Nakasongola',12),
    ('Lwemiyaga',13),
    ('Mawogola',13),
    ('Buikwe South',1),
    ('Buikwe West',1),
    ('Butambala',14),
    ('Bukoto Mid West',15),
    ('Bukoto South',15),
    ('Bukoto West',15),
    ('Kakuuto',16),
    ('Kooki',16),
    ('Kyotera',16),
    ('Buliisa',17),
    ('Bughendera',18),
    ('Bwamba',18),
    ('Bugahya',19),
    ('Buhaguzi',19),
    ('Ibanda N. (Ishongororo)',20),
    ('Ibanda South',20),
    ('Bukanga (Rugaaga)',21),
    ('Isingiro N. (Nyamuyanja)',21),
    ('Isingiro South (Kabuyanda)',21),
    ('Kabale Municipality',22),
    ('Ndorwa East',22),
    ('Ndorwa West (Rubaya)',22),
    ('Rubanda East',23),
    ('Rubanda West',23),
    ('Rukiga North',22),
    ('Rukiga South',22),
    ('Burahya',24),
    ('Fort Portal Municipality',24),
    ('Kibiito (Bunyangabu)',24),
    ('Kibale (Rukunyu)',25),
    ('Kitagwenda (Ntara)',25),
    ('Bukonzo East',26),
    ('Bukonzo West',26),
    ('Busongora North',26),
    ('Busongora South',26),
    ('Bugangaizi East',27),
    ('Bugangaizi West',27),
    ('Buyaga West',28),
    ('Buyaga East',28),
    ('Buyanja',29),
    ('Kazo',30),
    ('Nyabushozi',30),
    ('Bufumbira East',31),
    ('Bufumbira North',31),
    ('Bufumbira South',31),
    ('Mwenge North (Kyarusozi)',32),
    ('Mwenge South (Kyenjojo)',32),
    ('Kashaari (Bwizibwera)',33),
    ('Mbarara Municipality',33),
    ('Rwampara',33),
    ('Rubabo',34),
    ('Rujumbura',34),
    ('Kwania',35),
    ('Oyam North',36),
    ('Oyam South',36),
    ('West Moyo',37),
    ('Maracha',38),
    ('Labwor',39),
    ('Padyere',40),
    ('Aruu (Pajule)',41),
    ('Kioga',42),
    ('Maruzi',35),
    ('Obongi',37),
    ('Jonam',40),
    ('Koboko',43),
    ('Butembe',44),
    ('Jinja Municipality East',44),
    ('Jinja Municipality West',44),
    ('Kagoma',44),
    ('Kiira',44),
    ('Amuria',45),
    ('Kapelebyong',45),
    ('Bukooli Central',46),
    ('Bukooli North',46),
    ('Bukedea',47),
    ('Kongasis',48),
    ('Bunyole',49),
    ('Kaberamaido',50),
    ('Kalaki',50),
    ('Tingey',51),
    ('Usuk',52),
    ('Kumi',53),
    ('Bubulo East',54),
    ('Bubulo West',54),
    ('Bunya East',55),
    ('Bunya South',55),
    ('Bunya West',55),
    ('Bungokho North',56),
    ('Bungokho South',56),
    ('Mbale Municipality',56),
    ('Busiki',57),
    ('Ngora',58),
    ('Butebo',59),
    ('Pallisa',59),
    ('Soroti Municipality',60),
    ('Kisoko N. (West Budama N.)',61),
    ('Tororo County',61),
    ('Tororo Municipality',61),
    ('West Budama South',61),
    ('Soroti',60),
    ('Kasilo',62),
    ('Serere',62),
    ('Buvuma',63),
    ('Bujumba',64),
    ('Kyamuswa',64),
    ('Central',65),
    ('Kawempe',65),
    ('Makindye',65),
    ('Nakawa',65),
    ('Rubaga',65),
    ('Bukomero',66),
    ('Kiboga Central',66),
    ('Ntwetwe',67),
    ('Buwekula',68),
    ('Kassanda North',68),
    ('Kassanda South',68),
    ('Nakaseke North',69),
    ('Nakaseke South',69),
    ('Busiro East',70),
    ('Busiro North',70),
    ('Busiro South',70),
    ('Entebbe Municipality',70),
    ('Kyadondo East',70),
    ('Kyadondo North',70),
    ('Kyadondo South',70),
    ('Budaka',71),
    ('Iki Iki',71),
    ('Manjia',72),
    ('Bulambuli',73),
    ('Busia Municipality',74),
    ('Samia Bugwe North',74),
    ('Samia Bugwe South',74),
    ('Budiope',75),
    ('Bugweri',76),
    ('Iganga Municipality',76),
    ('Kigulu North',76),
    ('Kigulu South',76),
    ('Bulamogi',77),
    ('Bugabula North',78),
    ('Bugabula South',78),
    ('Buzaaya',78),
    ('Kibuku',79),
    ('Kween',80),
    ('Luuka',81),
    ('Bukooli South',82),
    ('Budadiri East',83),
    ('Budadiri West',83),
    ('East Moyo',84),
    ('Agago',85),
    ('Moroto',86),
    ('Pokot',87),
    ('Kilak',88),
    ('Arua Municipality',89),
    ('Ayivu',89),
    ('Lower Madi',89),
    ('Vurra',89),
    ('Terego',89),
    ('Dokolo',90),
    ('Aswa',91),
    ('Gulu Municipality',91),
    ('Omoro',92),
    ('Dodoth East',93),
    ('Dodoth West',93),
    ('Chua',94),
    ('Kole',95),
    ('Jie',96),
    ('Lamwo',97),
    ('Erute North',98),
    ('Erute South',98),
    ('Lira Municipality',98),
    ('Matheniko',99),
    ('Moroto Municipality',99),
    ('Chekwii',100),
    ('Pian',100),
    ('Bokora',101),
    ('Nwoya',102),
    ('Otuke',103),
    ('Aringa',104),
    ('Okoro',105),
    ('Buhweju',106),
    ('Igara East',107),
    ('Igara West',107),
    ('Ishaka Bushenyi Municipality',107),
    ('Hoima Municipality',19),
    ('Kinkizi East',108),
    ('Kinkizi West',108),
    ('Kibanda',109),
    ('Kyaka',110),
    ('Bujenje',111),
    ('Buruli',111),
    ('Masindi Municipality',111),
    ('Ruhinda',112),
    ('Ntoroko',113),
    ('Kajara',114),
    ('Ruhaama',114),
    ('Rushenyi',114),
    ('Bunyaruguru',115),
    ('Katerera',115),
    ('Sheema North',116),
    ('Sheema South',116)");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('health_sub_districts');
    }
};
