name: LabSpars CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, intl, sqlite, pdo_sqlite, pcntl, redis
        coverage: none

    - name: Cache Composer
      uses: actions/cache@v3
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Create environment file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Setup SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=$(pwd)/database/database.sqlite" >> .env

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run test suite
      run: php artisan test --testsuite=Unit --testsuite=Feature

          - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: storage/logs/

